services:
  leitor_doc_pyzerox:
    image: andersonlemes/leitor_doc_pyzerox:latest
    networks:
      - network_public
    environment:
      # Seleção do provedor de IA: openai, gemini, anthropic, deepseek, grok, llama_local
      - AI_PROVIDER=openai
      
      # Configurações da OpenAI (padrão)
      - OPENAI_API_KEY=sk-xxx
      - OPENAI_MODEL=gpt-4o-mini
      
      # Configurações gerais
      - WORKERS=4 # (2 x num_cores) + 1
      - TIMEOUT=0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 760M
      labels:
        - traefik.enable=true
        - traefik.http.routers.leitor_doc_pyzerox.rule=Host(`api.doc2md.website.com`)
        - traefik.http.routers.leitor_doc_pyzerox.entrypoints=websecure
        - traefik.http.routers.leitor_doc_pyzerox.tls.certresolver=letsencryptresolver
        - traefik.http.routers.leitor_doc_pyzerox.priority=1
        - traefik.http.routers.leitor_doc_pyzerox.service=leitor_doc_pyzerox
        - traefik.http.services.leitor_doc_pyzerox.loadbalancer.server.port=5000
        - traefik.http.services.leitor_doc_pyzerox.loadbalancer.passHostHeader=true
networks:
  network_public:
    name: network_public
    external: true
